export const vData = "Voltage Data";

export const voltageColumns = [
      // { field: "id", headerName: "id", width: 130 },
      { field: "SerialNo", headerName: "Serial No.", width: 130 },
      {
        field: "Timestamp",
        headerName: "Timestamp",
        width: 290,
      },
      // {
      //   field: "DCCurrent",
      //   headerName: "DC Current",
      //   width: 290,
      // },
      // {
      //   field: "ACCurrent",
      //   headerName: "AC Current",
      //   width: 290,
      // },
      {
        field: "DCVoltage",
        headerName: "DC Voltage",
        width: 290,
      },
      {
        field: "ACVoltage",
        headerName: "AC Voltage",
        width: 290,
      },
      // {
      //   field: "ActivePower",
      //   headerName: "Active Power",
      //   width: 290,
      // },
      // {
      //   field: "ReactivePower",
      //   headerName: "Reactive Power",
      //   width: 290,
      // },
    ];
  
  //temporary data
  export const voltageRows = [
    {
      id: 1,
      timestamps: "07-02-2023 18:17",
      dcVoltage: 10,
      phaseVoltageR: 20,
      phaseVoltageY: 30,
      phaseVoltageB: 40,
      phaseVoltageN: 100,
    },
    {
      id: 2,
      timestamps: "07-02-2023 18:17",
      dcVoltage: 10,
      phaseVoltageR: 20,
      phaseVoltageY: 30,
      phaseVoltageB: 40,
      phaseVoltageN: 100,
    },
    {
      id: 3,
      timestamps: "07-02-2023 18:17",
      dcVoltage: 10,
      phaseVoltageR: 20,
      phaseVoltageY: 30,
      phaseVoltageB: 40,
      phaseVoltageN: 100,
    },
    {
      id: 4,
      timestamps: "07-02-2023 18:17",
      dcVoltage: 10,
      phaseVoltageR: 20,
      phaseVoltageY: 30,
      phaseVoltageB: 40,
      phaseVoltageN: 100,
    },
    {
      id: 5,
      timestamps: "07-02-2023 18:17",
      dcVoltage: 10,
      phaseVoltageR: 20,
      phaseVoltageY: 30,
      phaseVoltageB: 40,
      phaseVoltageN: 100,
    },
    {
      id: 6,
      timestamps: "07-02-2023 18:17",
      dcVoltage: 10,
      phaseVoltageR: 20,
      phaseVoltageY: 30,
      phaseVoltageB: 40,
      phaseVoltageN: 100,
    },
    {
      id: 7,
      timestamps: "07-02-2023 18:17",
      dcVoltage: 10,
      phaseVoltageR: 20,
      phaseVoltageY: 30,
      phaseVoltageB: 40,
      phaseVoltageN: 100,
    },
    {
      id: 8,
      timestamps: "07-02-2023 18:17",
      dcVoltage: 10,
      phaseVoltageR: 20,
      phaseVoltageY: 30,
      phaseVoltageB: 40,
      phaseVoltageN: 100,
    },
    {
      id: 9,
      timestamps: "07-02-2023 18:17",
      dcVoltage: 10,
      phaseVoltageR: 20,
      phaseVoltageY: 30,
      phaseVoltageB: 40,
      phaseVoltageN: 100,
    },
    {
      id: 10,
      timestamps: "07-02-2023 18:17",
      dcVoltage: 10,
      phaseVoltageR: 20,
      phaseVoltageY: 30,
      phaseVoltageB: 40,
      phaseVoltageN: 100,
    },
  ];
  